provider: azuread
major-version: 6
generate-nightly-test-workflow: true
esc:
    enabled: true
env:
    ARM_CLIENT_ID: "d3b6ec3a-36fe-46c9-b3d9-5856a2e0e73c" # test-app
    ARM_ENVIRONMENT: "public"
    ARM_SUBSCRIPTION_ID: "0282681f-7a9e-424b-80b2-96babd57a8a1"
    ARM_TENANT_ID: "9605c22c-e585-4ea3-9b83-e90339719f8a" # pulumici.onmicrosoft.com
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_CI }}
    # Setting this variable will cause the OIDC test(s) to run against this app.
    # We limit running the OIDC tests to PRs because the AD configuration requires an "Entity type" of Environment,
    # Branch, Pull request, or Tag. See
    # https://learn.microsoft.com/en-us/azure/active-directory/workload-identities/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#github-actions
    RUN_OIDC_TESTS: ${{ github.event_name == 'pull_request' && 'true' || '' }}
makeTemplate: bridged
team: ecosystem
license:
    ignore:
        - github.com/hashicorp/terraform-provider-azuread/shim
allowMissingDocs: false
# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
releaseVerification:
    nodejs: examples/release-verification/ts/user
    python: examples/release-verification/py/user
    dotnet: examples/release-verification/cs/user
    go: examples/release-verification/go/user
autoMergeProviderUpgrades: false
