provider: azuread
major-version: 5
generate-nightly-test-workflow: true
esc:
    enabled: true
env:
    # Setting this variable will cause the OIDC test(s) to run against this app.
    # We limit running the OIDC tests to PRs because the AD configuration requires an "Entity type" of Environment,
    # Branch, Pull request, or Tag. See
    # https://learn.microsoft.com/en-us/azure/active-directory/workload-identities/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#github-actions
    RUN_OIDC_TESTS: ${{ github.event_name == 'pull_request' && 'true' || '' }}
makeTemplate: bridged
team: ecosystem
license:
    ignore:
        - github.com/hashicorp/terraform-provider-azuread/shim
# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
