provider: azuread
major-version: 5
generate-nightly-test-workflow: true
env:
  ARM_CLIENT_ID: "30e520fa-12b4-4e21-b473-9426c5ac2e1e"
  ARM_ENVIRONMENT: "public"
  ARM_SUBSCRIPTION_ID: "0282681f-7a9e-424b-80b2-96babd57a8a1"
  ARM_TENANT_ID: "706143bc-e1d4-4593-aee2-c9dc60ab9be7"
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  OIDC_ARM_CLIENT_ID: ${{ github.event_name == 'pull_request' && '89380e12-5be6-486a-89ef-eea107af2f47' || '' }}
makeTemplate: bridged
team: ecosystem
plugins:
  - name: time
    version: "0.0.15"
  - name: std
    version: "1.4.0"
  - name: azure
    version: "5.52.0"
  - name: random
    version: "4.14.0"
javaGenVersion: "v0.9.7"
license:
  ignore:
    - github.com/hashicorp/terraform-provider-azuread/shim
