// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureAD.Outputs
{

    [OutputType]
    public sealed class GetApplicationOptionalClaimResult
    {
        /// <summary>
        /// One or more `access_token` blocks as documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetApplicationOptionalClaimAccessTokenResult> AccessTokens;
        /// <summary>
        /// One or more `id_token` blocks as documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetApplicationOptionalClaimIdTokenResult> IdTokens;
        /// <summary>
        /// One or more `saml2_token` blocks as documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetApplicationOptionalClaimSaml2TokenResult> Saml2Tokens;

        [OutputConstructor]
        private GetApplicationOptionalClaimResult(
            ImmutableArray<Outputs.GetApplicationOptionalClaimAccessTokenResult> accessTokens,

            ImmutableArray<Outputs.GetApplicationOptionalClaimIdTokenResult> idTokens,

            ImmutableArray<Outputs.GetApplicationOptionalClaimSaml2TokenResult> saml2Tokens)
        {
            AccessTokens = accessTokens;
            IdTokens = idTokens;
            Saml2Tokens = saml2Tokens;
        }
    }
}
