// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureAD.Outputs
{

    [OutputType]
    public sealed class GetApplicationAppRoleResult
    {
        /// <summary>
        /// Specifies whether this app role definition can be assigned to users and groups, or to other applications (that are accessing this application in a standalone scenario). Possible values are: `User` and `Application`, or both.
        /// </summary>
        public readonly ImmutableArray<string> AllowedMemberTypes;
        /// <summary>
        /// Description of the app role that appears when the role is being assigned and, if the role functions as an application permissions, during the consent experiences.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Specifies the display name of the application.
        /// </summary>
        public readonly string DisplayName;
        /// <summary>
        /// (Optional) Determines if the permission scope is enabled.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// The unique identifier for one of the `OAuth2Permission` or `AppRole` instances that the resource application exposes.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Is this permission enabled?
        /// </summary>
        public readonly bool IsEnabled;
        /// <summary>
        /// The name of this permission
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetApplicationAppRoleResult(
            ImmutableArray<string> allowedMemberTypes,

            string description,

            string displayName,

            bool enabled,

            string id,

            bool isEnabled,

            string value)
        {
            AllowedMemberTypes = allowedMemberTypes;
            Description = description;
            DisplayName = displayName;
            Enabled = enabled;
            Id = id;
            IsEnabled = isEnabled;
            Value = value;
        }
    }
}
