// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package azuread

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to access information about an Application Template from the [Azure AD App Gallery](https://azuremarketplace.microsoft.com/en-US/marketplace/apps/category/azure-active-directory-apps).
//
// ## API Permissions
//
// This data source does not require any additional roles.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-azuread/sdk/v5/go/azuread"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "Marketo"
// 		example, err := azuread.GetApplicationTemplate(ctx, &GetApplicationTemplateArgs{
// 			DisplayName: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("applicationTemplateId", example.TemplateId)
// 		return nil
// 	})
// }
// ```
func GetApplicationTemplate(ctx *pulumi.Context, args *GetApplicationTemplateArgs, opts ...pulumi.InvokeOption) (*GetApplicationTemplateResult, error) {
	var rv GetApplicationTemplateResult
	err := ctx.Invoke("azuread:index/getApplicationTemplate:getApplicationTemplate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApplicationTemplate.
type GetApplicationTemplateArgs struct {
	// Specifies the display name of the templated application.
	DisplayName *string `pulumi:"displayName"`
	// Specifies the ID of the templated application.
	TemplateId *string `pulumi:"templateId"`
}

// A collection of values returned by getApplicationTemplate.
type GetApplicationTemplateResult struct {
	// List of categories for this templated application.
	Categories []string `pulumi:"categories"`
	// The display name for the templated application.
	DisplayName string `pulumi:"displayName"`
	// Home page URL of the templated application.
	HomepageUrl string `pulumi:"homepageUrl"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// URL to retrieve the logo for this templated application.
	LogoUrl string `pulumi:"logoUrl"`
	// Name of the publisher for this templated application.
	Publisher string `pulumi:"publisher"`
	// List of provisioning modes supported by this templated application.
	SupportedProvisioningTypes []string `pulumi:"supportedProvisioningTypes"`
	// List of single sign on modes supported by this templated application.
	SupportedSingleSignOnModes []string `pulumi:"supportedSingleSignOnModes"`
	// The ID of the templated application.
	TemplateId string `pulumi:"templateId"`
}
