// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package azuread

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetServicePrincipals(ctx *pulumi.Context, args *GetServicePrincipalsArgs, opts ...pulumi.InvokeOption) (*GetServicePrincipalsResult, error) {
	var rv GetServicePrincipalsResult
	err := ctx.Invoke("azuread:index/getServicePrincipals:getServicePrincipals", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServicePrincipals.
type GetServicePrincipalsArgs struct {
	ApplicationIds []string `pulumi:"applicationIds"`
	DisplayNames   []string `pulumi:"displayNames"`
	IgnoreMissing  *bool    `pulumi:"ignoreMissing"`
	ObjectIds      []string `pulumi:"objectIds"`
	ReturnAll      *bool    `pulumi:"returnAll"`
}

// A collection of values returned by getServicePrincipals.
type GetServicePrincipalsResult struct {
	ApplicationIds []string `pulumi:"applicationIds"`
	DisplayNames   []string `pulumi:"displayNames"`
	// The provider-assigned unique ID for this managed resource.
	Id                string                                 `pulumi:"id"`
	IgnoreMissing     *bool                                  `pulumi:"ignoreMissing"`
	ObjectIds         []string                               `pulumi:"objectIds"`
	ReturnAll         *bool                                  `pulumi:"returnAll"`
	ServicePrincipals []GetServicePrincipalsServicePrincipal `pulumi:"servicePrincipals"`
}

func GetServicePrincipalsOutput(ctx *pulumi.Context, args GetServicePrincipalsOutputArgs, opts ...pulumi.InvokeOption) GetServicePrincipalsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetServicePrincipalsResult, error) {
			args := v.(GetServicePrincipalsArgs)
			r, err := GetServicePrincipals(ctx, &args, opts...)
			var s GetServicePrincipalsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetServicePrincipalsResultOutput)
}

// A collection of arguments for invoking getServicePrincipals.
type GetServicePrincipalsOutputArgs struct {
	ApplicationIds pulumi.StringArrayInput `pulumi:"applicationIds"`
	DisplayNames   pulumi.StringArrayInput `pulumi:"displayNames"`
	IgnoreMissing  pulumi.BoolPtrInput     `pulumi:"ignoreMissing"`
	ObjectIds      pulumi.StringArrayInput `pulumi:"objectIds"`
	ReturnAll      pulumi.BoolPtrInput     `pulumi:"returnAll"`
}

func (GetServicePrincipalsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServicePrincipalsArgs)(nil)).Elem()
}

// A collection of values returned by getServicePrincipals.
type GetServicePrincipalsResultOutput struct{ *pulumi.OutputState }

func (GetServicePrincipalsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServicePrincipalsResult)(nil)).Elem()
}

func (o GetServicePrincipalsResultOutput) ToGetServicePrincipalsResultOutput() GetServicePrincipalsResultOutput {
	return o
}

func (o GetServicePrincipalsResultOutput) ToGetServicePrincipalsResultOutputWithContext(ctx context.Context) GetServicePrincipalsResultOutput {
	return o
}

func (o GetServicePrincipalsResultOutput) ApplicationIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) []string { return v.ApplicationIds }).(pulumi.StringArrayOutput)
}

func (o GetServicePrincipalsResultOutput) DisplayNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) []string { return v.DisplayNames }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetServicePrincipalsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetServicePrincipalsResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

func (o GetServicePrincipalsResultOutput) ObjectIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) []string { return v.ObjectIds }).(pulumi.StringArrayOutput)
}

func (o GetServicePrincipalsResultOutput) ReturnAll() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) *bool { return v.ReturnAll }).(pulumi.BoolPtrOutput)
}

func (o GetServicePrincipalsResultOutput) ServicePrincipals() GetServicePrincipalsServicePrincipalArrayOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) []GetServicePrincipalsServicePrincipal { return v.ServicePrincipals }).(GetServicePrincipalsServicePrincipalArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServicePrincipalsResultOutput{})
}
