// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azuread;

import com.pulumi.azuread.inputs.SynchronizationJobProvisionOnDemandParameterArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SynchronizationJobProvisionOnDemandArgs extends com.pulumi.resources.ResourceArgs {

    public static final SynchronizationJobProvisionOnDemandArgs Empty = new SynchronizationJobProvisionOnDemandArgs();

    /**
     * One or more `parameter` blocks as documented below.
     * 
     */
    @Import(name="parameters", required=true)
    private Output<List<SynchronizationJobProvisionOnDemandParameterArgs>> parameters;

    /**
     * @return One or more `parameter` blocks as documented below.
     * 
     */
    public Output<List<SynchronizationJobProvisionOnDemandParameterArgs>> parameters() {
        return this.parameters;
    }

    /**
     * The object ID of the service principal for the synchronization job.
     * 
     */
    @Import(name="servicePrincipalId", required=true)
    private Output<String> servicePrincipalId;

    /**
     * @return The object ID of the service principal for the synchronization job.
     * 
     */
    public Output<String> servicePrincipalId() {
        return this.servicePrincipalId;
    }

    /**
     * Identifier of the synchronization template this job is based on.
     * 
     */
    @Import(name="synchronizationJobId", required=true)
    private Output<String> synchronizationJobId;

    /**
     * @return Identifier of the synchronization template this job is based on.
     * 
     */
    public Output<String> synchronizationJobId() {
        return this.synchronizationJobId;
    }

    @Import(name="triggers")
    private @Nullable Output<Map<String,String>> triggers;

    public Optional<Output<Map<String,String>>> triggers() {
        return Optional.ofNullable(this.triggers);
    }

    private SynchronizationJobProvisionOnDemandArgs() {}

    private SynchronizationJobProvisionOnDemandArgs(SynchronizationJobProvisionOnDemandArgs $) {
        this.parameters = $.parameters;
        this.servicePrincipalId = $.servicePrincipalId;
        this.synchronizationJobId = $.synchronizationJobId;
        this.triggers = $.triggers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SynchronizationJobProvisionOnDemandArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SynchronizationJobProvisionOnDemandArgs $;

        public Builder() {
            $ = new SynchronizationJobProvisionOnDemandArgs();
        }

        public Builder(SynchronizationJobProvisionOnDemandArgs defaults) {
            $ = new SynchronizationJobProvisionOnDemandArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param parameters One or more `parameter` blocks as documented below.
         * 
         * @return builder
         * 
         */
        public Builder parameters(Output<List<SynchronizationJobProvisionOnDemandParameterArgs>> parameters) {
            $.parameters = parameters;
            return this;
        }

        /**
         * @param parameters One or more `parameter` blocks as documented below.
         * 
         * @return builder
         * 
         */
        public Builder parameters(List<SynchronizationJobProvisionOnDemandParameterArgs> parameters) {
            return parameters(Output.of(parameters));
        }

        /**
         * @param parameters One or more `parameter` blocks as documented below.
         * 
         * @return builder
         * 
         */
        public Builder parameters(SynchronizationJobProvisionOnDemandParameterArgs... parameters) {
            return parameters(List.of(parameters));
        }

        /**
         * @param servicePrincipalId The object ID of the service principal for the synchronization job.
         * 
         * @return builder
         * 
         */
        public Builder servicePrincipalId(Output<String> servicePrincipalId) {
            $.servicePrincipalId = servicePrincipalId;
            return this;
        }

        /**
         * @param servicePrincipalId The object ID of the service principal for the synchronization job.
         * 
         * @return builder
         * 
         */
        public Builder servicePrincipalId(String servicePrincipalId) {
            return servicePrincipalId(Output.of(servicePrincipalId));
        }

        /**
         * @param synchronizationJobId Identifier of the synchronization template this job is based on.
         * 
         * @return builder
         * 
         */
        public Builder synchronizationJobId(Output<String> synchronizationJobId) {
            $.synchronizationJobId = synchronizationJobId;
            return this;
        }

        /**
         * @param synchronizationJobId Identifier of the synchronization template this job is based on.
         * 
         * @return builder
         * 
         */
        public Builder synchronizationJobId(String synchronizationJobId) {
            return synchronizationJobId(Output.of(synchronizationJobId));
        }

        public Builder triggers(@Nullable Output<Map<String,String>> triggers) {
            $.triggers = triggers;
            return this;
        }

        public Builder triggers(Map<String,String> triggers) {
            return triggers(Output.of(triggers));
        }

        public SynchronizationJobProvisionOnDemandArgs build() {
            if ($.parameters == null) {
                throw new MissingRequiredPropertyException("SynchronizationJobProvisionOnDemandArgs", "parameters");
            }
            if ($.servicePrincipalId == null) {
                throw new MissingRequiredPropertyException("SynchronizationJobProvisionOnDemandArgs", "servicePrincipalId");
            }
            if ($.synchronizationJobId == null) {
                throw new MissingRequiredPropertyException("SynchronizationJobProvisionOnDemandArgs", "synchronizationJobId");
            }
            return $;
        }
    }

}
