// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azuread.outputs;

import com.pulumi.azuread.outputs.GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAdminNotifications;
import com.pulumi.azuread.outputs.GroupRoleManagementPolicyNotificationRulesActiveAssignmentsApproverNotifications;
import com.pulumi.azuread.outputs.GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAssigneeNotifications;
import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GroupRoleManagementPolicyNotificationRulesActiveAssignments {
    /**
     * @return Admin notification settings
     * 
     */
    private @Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAdminNotifications adminNotifications;
    /**
     * @return Approver notification settings
     * 
     */
    private @Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsApproverNotifications approverNotifications;
    /**
     * @return Assignee notification settings
     * 
     */
    private @Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAssigneeNotifications assigneeNotifications;

    private GroupRoleManagementPolicyNotificationRulesActiveAssignments() {}
    /**
     * @return Admin notification settings
     * 
     */
    public Optional<GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAdminNotifications> adminNotifications() {
        return Optional.ofNullable(this.adminNotifications);
    }
    /**
     * @return Approver notification settings
     * 
     */
    public Optional<GroupRoleManagementPolicyNotificationRulesActiveAssignmentsApproverNotifications> approverNotifications() {
        return Optional.ofNullable(this.approverNotifications);
    }
    /**
     * @return Assignee notification settings
     * 
     */
    public Optional<GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAssigneeNotifications> assigneeNotifications() {
        return Optional.ofNullable(this.assigneeNotifications);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GroupRoleManagementPolicyNotificationRulesActiveAssignments defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAdminNotifications adminNotifications;
        private @Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsApproverNotifications approverNotifications;
        private @Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAssigneeNotifications assigneeNotifications;
        public Builder() {}
        public Builder(GroupRoleManagementPolicyNotificationRulesActiveAssignments defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.adminNotifications = defaults.adminNotifications;
    	      this.approverNotifications = defaults.approverNotifications;
    	      this.assigneeNotifications = defaults.assigneeNotifications;
        }

        @CustomType.Setter
        public Builder adminNotifications(@Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAdminNotifications adminNotifications) {

            this.adminNotifications = adminNotifications;
            return this;
        }
        @CustomType.Setter
        public Builder approverNotifications(@Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsApproverNotifications approverNotifications) {

            this.approverNotifications = approverNotifications;
            return this;
        }
        @CustomType.Setter
        public Builder assigneeNotifications(@Nullable GroupRoleManagementPolicyNotificationRulesActiveAssignmentsAssigneeNotifications assigneeNotifications) {

            this.assigneeNotifications = assigneeNotifications;
            return this;
        }
        public GroupRoleManagementPolicyNotificationRulesActiveAssignments build() {
            final var _resultValue = new GroupRoleManagementPolicyNotificationRulesActiveAssignments();
            _resultValue.adminNotifications = adminNotifications;
            _resultValue.approverNotifications = approverNotifications;
            _resultValue.assigneeNotifications = assigneeNotifications;
            return _resultValue;
        }
    }
}
