// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureAD.Inputs
{

    public sealed class AccessPackageAssignmentPolicyQuestionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("choices")]
        private InputList<Inputs.AccessPackageAssignmentPolicyQuestionChoiceGetArgs>? _choices;

        /// <summary>
        /// One or more blocks configuring a choice to the question, as documented below.
        /// </summary>
        public InputList<Inputs.AccessPackageAssignmentPolicyQuestionChoiceGetArgs> Choices
        {
            get => _choices ?? (_choices = new InputList<Inputs.AccessPackageAssignmentPolicyQuestionChoiceGetArgs>());
            set => _choices = value;
        }

        /// <summary>
        /// Whether this question is required.
        /// </summary>
        [Input("required")]
        public Input<bool>? Required { get; set; }

        /// <summary>
        /// The sequence number of this question.
        /// </summary>
        [Input("sequence")]
        public Input<int>? Sequence { get; set; }

        /// <summary>
        /// A block describing the content of this question, as documented below.
        /// </summary>
        [Input("text", required: true)]
        public Input<Inputs.AccessPackageAssignmentPolicyQuestionTextGetArgs> Text { get; set; } = null!;

        public AccessPackageAssignmentPolicyQuestionGetArgs()
        {
        }
        public static new AccessPackageAssignmentPolicyQuestionGetArgs Empty => new AccessPackageAssignmentPolicyQuestionGetArgs();
    }
}
