// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureAD.Inputs
{

    public sealed class AccessPackageAssignmentPolicyRequestorSettingsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("requestors")]
        private InputList<Inputs.AccessPackageAssignmentPolicyRequestorSettingsRequestorGetArgs>? _requestors;
        public InputList<Inputs.AccessPackageAssignmentPolicyRequestorSettingsRequestorGetArgs> Requestors
        {
            get => _requestors ?? (_requestors = new InputList<Inputs.AccessPackageAssignmentPolicyRequestorSettingsRequestorGetArgs>());
            set => _requestors = value;
        }

        [Input("requestsAccepted")]
        public Input<bool>? RequestsAccepted { get; set; }

        [Input("scopeType")]
        public Input<string>? ScopeType { get; set; }

        public AccessPackageAssignmentPolicyRequestorSettingsGetArgs()
        {
        }
        public static new AccessPackageAssignmentPolicyRequestorSettingsGetArgs Empty => new AccessPackageAssignmentPolicyRequestorSettingsGetArgs();
    }
}
