// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a FIDO2 combination configuration for an authentication strength policy within Azure Active Directory.
 *
 * A FIDO2 combination configuration restricts which security keys, identified by their Authenticator Attestation GUID (AAGUID), satisfy the `fido2` authentication method combination. A policy supports at most one FIDO2 combination configuration.
 *
 * ## API Permissions
 *
 * The following API permissions are required in order to use this resource.
 *
 * When authenticated with a service principal, this resource requires the following application roles: `Policy.ReadWrite.ConditionalAccess` and `Policy.Read.All`
 *
 * When authenticated with a user principal, this resource requires one of the following directory roles: `Conditional Access Administrator` or `Global Administrator`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azuread from "@pulumi/azuread";
 *
 * const example = new azuread.AuthenticationStrengthPolicy("example", {
 *     displayName: "Example Authentication Strength Policy",
 *     description: "Policy for demo purposes",
 *     allowedCombinations: ["fido2"],
 * });
 * const exampleAuthenticationStrengthPolicyFido2CombinationConfiguration = new azuread.AuthenticationStrengthPolicyFido2CombinationConfiguration("example", {
 *     authenticationStrengthPolicyId: example.objectId,
 *     allowedAaguids: [
 *         "de1e552d-db1d-4423-a619-566b625cdc84",
 *         "90a3ccdf-635c-4729-a248-9b709135078f",
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * FIDO2 combination configurations can be imported using the `id`, e.g.
 *
 * ```sh
 * $ pulumi import azuread:index/authenticationStrengthPolicyFido2CombinationConfiguration:AuthenticationStrengthPolicyFido2CombinationConfiguration example /policies/authenticationStrengthPolicies/00000000-0000-0000-0000-000000000000/combinationConfigurations/11111111-1111-1111-1111-111111111111
 * ```
 */
export class AuthenticationStrengthPolicyFido2CombinationConfiguration extends pulumi.CustomResource {
    /**
     * Get an existing AuthenticationStrengthPolicyFido2CombinationConfiguration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AuthenticationStrengthPolicyFido2CombinationConfigurationState, opts?: pulumi.CustomResourceOptions): AuthenticationStrengthPolicyFido2CombinationConfiguration {
        return new AuthenticationStrengthPolicyFido2CombinationConfiguration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'azuread:index/authenticationStrengthPolicyFido2CombinationConfiguration:AuthenticationStrengthPolicyFido2CombinationConfiguration';

    /**
     * Returns true if the given object is an instance of AuthenticationStrengthPolicyFido2CombinationConfiguration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AuthenticationStrengthPolicyFido2CombinationConfiguration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AuthenticationStrengthPolicyFido2CombinationConfiguration.__pulumiType;
    }

    /**
     * A set of Authenticator Attestation GUIDs (AAGUIDs) allowed to satisfy the `fido2` combination.
     */
    declare public readonly allowedAaguids: pulumi.Output<string[]>;
    /**
     * The object ID of the authentication strength policy to which this combination configuration applies. Changing this field forces a new resource to be created.
     *
     * > The associated authentication strength policy must specify `fido2` in its `allowedCombinations`, otherwise the API rejects the combination configuration.
     */
    declare public readonly authenticationStrengthPolicyId: pulumi.Output<string>;

    /**
     * Create a AuthenticationStrengthPolicyFido2CombinationConfiguration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AuthenticationStrengthPolicyFido2CombinationConfigurationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AuthenticationStrengthPolicyFido2CombinationConfigurationArgs | AuthenticationStrengthPolicyFido2CombinationConfigurationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AuthenticationStrengthPolicyFido2CombinationConfigurationState | undefined;
            resourceInputs["allowedAaguids"] = state?.allowedAaguids;
            resourceInputs["authenticationStrengthPolicyId"] = state?.authenticationStrengthPolicyId;
        } else {
            const args = argsOrState as AuthenticationStrengthPolicyFido2CombinationConfigurationArgs | undefined;
            if (args?.allowedAaguids === undefined && !opts.urn) {
                throw new Error("Missing required property 'allowedAaguids'");
            }
            if (args?.authenticationStrengthPolicyId === undefined && !opts.urn) {
                throw new Error("Missing required property 'authenticationStrengthPolicyId'");
            }
            resourceInputs["allowedAaguids"] = args?.allowedAaguids;
            resourceInputs["authenticationStrengthPolicyId"] = args?.authenticationStrengthPolicyId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AuthenticationStrengthPolicyFido2CombinationConfiguration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AuthenticationStrengthPolicyFido2CombinationConfiguration resources.
 */
export interface AuthenticationStrengthPolicyFido2CombinationConfigurationState {
    /**
     * A set of Authenticator Attestation GUIDs (AAGUIDs) allowed to satisfy the `fido2` combination.
     */
    allowedAaguids?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The object ID of the authentication strength policy to which this combination configuration applies. Changing this field forces a new resource to be created.
     *
     * > The associated authentication strength policy must specify `fido2` in its `allowedCombinations`, otherwise the API rejects the combination configuration.
     */
    authenticationStrengthPolicyId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AuthenticationStrengthPolicyFido2CombinationConfiguration resource.
 */
export interface AuthenticationStrengthPolicyFido2CombinationConfigurationArgs {
    /**
     * A set of Authenticator Attestation GUIDs (AAGUIDs) allowed to satisfy the `fido2` combination.
     */
    allowedAaguids: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The object ID of the authentication strength policy to which this combination configuration applies. Changing this field forces a new resource to be created.
     *
     * > The associated authentication strength policy must specify `fido2` in its `allowedCombinations`, otherwise the API rejects the combination configuration.
     */
    authenticationStrengthPolicyId: pulumi.Input<string>;
}
